export { default as testimonialValidations } from './testimonial.validations'
export { default as newValidations } from './new.validations'
export { default as idValidation } from './id.validation'
export { default as authValidation } from './auth.validations'
export { default as contactValidation } from './contact.validations'
